island.width=100
island.height=20
animal.data.file=src/main/resources/animals.yml
eating.chances.file=src/main/resources/eating-chances.yml
animals.per.type=5
simulation.plant.growth.interval=5
simulation.animal.lifecycle.interval=10
grass.initial.weight=5
grass.growth.rate=1
grass.max.weight=1000